version: '3' 
services:
    redis_db:
        image: 'redis'
        volumes:
        - ./data:/data
        - /usr/app/node_modules
        command: ["redis-server", "--save", "1 1"]
    node-app:
        build: ./
        image: "amitamish/visits"
        ports:
            - "8081:8081"
